name: build


on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  pull_request:
  workflow_call:

jobs:
  Build:
    name: ${{ matrix.os-name }} (${{ matrix.compiler }}, ${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        config: [Release, Debug]
        name: [windows-msvc, windows-clang, linux-clang, linux-gcc, macos-clang]
        include:
          - name: windows-msvc
            os: windows-latest
            os-name: windows
            compiler: msvc
            cxx: cl
            cc: cl
          - name: windows-clang
            os: windows-latest
            os-name: windows
            compiler: clang-16
            cxx: clang-cl
            cc: clang-cl
          - name: linux-clang
            os: ubuntu-latest
            os-name: linux
            compiler: clang-16
            cxx: clang++
            cc: clang
          - name: linux-gcc
            os: ubuntu-latest
            os-name: linux
            compiler: gcc-13
            cxx: g++
            cc: gcc
          - name: macos-clang
            os: macos-14
            os-name: macos
            compiler: clang-16
            cxx: clang++
            cc: clang
          #- name: macos-gcc
          #  os: macos-14
          #  os-name: macos
          #  compiler: gcc-13
          #  cxx: /usr/bin/g++
          #  cc: /usr/bin/gcc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ matrix.os-name == 'windows' }}
          cmake: true
          ninja: true

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: Build
          key: ${{ matrix.os-name }}-${{ matrix.compiler }}-${{ matrix.config }}-build-${{ secrets.VCACHE}}

      - name: Configure
        run: cmake -GNinja -S . -B Build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{matrix.cxx}} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/Install

      - name: Build
        run: cmake --build Build --config ${{ matrix.config }}

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        if: ${{ matrix.config == 'Release' && contains(matrix.compiler, 'clang') }} # Only clang artifacts are stored
        with:
          name: pipe-${{ matrix.os-name }}
          path: Build/Bin

      - name: Install
        run: cmake --install Build --config ${{ matrix.config }}

      - name: Upload installation
        uses: actions/upload-artifact@v3
        if: ${{ matrix.config == 'Release' && contains(matrix.compiler, 'clang') }} # Only clang artifacts are stored
        with:
          name: pipe-${{ matrix.os-name }}-install
          path: Install

      - name: Run Tests
        if: ${{ matrix.os-name != 'macos' }} # Tests are skipped temporarily on MacOS
        working-directory: ./Build
        run: ctest --output-on-failure -j2 -C ${{ matrix.config }}

  Deploy:
    needs: Build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download installation
        uses: actions/download-artifact@v3
        with:
          name: pipe-linux-install
          path: Install/Linux

      - name: Download installation
        uses: actions/download-artifact@v3
        with:
          name: pipe-windows-install
          path: Install/Windows

      - name: Upload all
        uses: actions/upload-artifact@v3
        with:
          name: pipe-all-install
          path: Install
