name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  pull_request:
  workflow_call:

jobs:
  Build:
    name: ${{ matrix.os-name }} (${{ matrix.compiler }}, ${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [windows-msvc, windows-clang, linux-clang, linux-gcc, macos-clang]
        config: [Release, Debug]
        include:
          - name: windows-msvc
            os: windows-latest
            os-name: windows
            compiler: msvc-17
          - name: windows-clang
            os: windows-latest
            os-name: windows
            compiler: clang-16
          - name: linux-clang
            os: ubuntu-latest
            os-name: linux
            compiler: clang-16
          - name: linux-gcc
            os: ubuntu-latest
            os-name: linux
            compiler: gcc-13
          - name: macos-clang
            os: macos-latest
            os-name: macos
            compiler: clang-17
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true

      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: Build
          key: ${{ matrix.os-name }}-${{ matrix.compiler }}-${{ matrix.config }}-build-${{ secrets.VCACHE}}

      - name: Configure
        run: cmake -S . -B Build -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        run: cmake --build Build --config ${{ matrix.config }}

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        if: ${{ matrix.config == 'Release' && contains(matrix.compiler, 'clang') }} # Only clang artifacts are stored
        with:
          name: pipe-${{ matrix.os-name }}
          path: Build/Bin

      - name: Run Tests
        if: ${{ matrix.os-name != 'macos' }} # Tests are skipped temporarily on MacOS
        working-directory: ./Build
        run: ctest --output-on-failure -j2 -C ${{ matrix.config }}
