name: publish-release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  Publish:
    needs: Package
    runs-on: ubuntu-latest
    steps:
      - name: Download Pipe build
        uses: actions/download-artifact@v4
        with:
          name: Pipe
          path: Pipe

      - name: Package
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: 'Pipe'
          filename: 'Pipe.zip'

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: Pipe.zip
